/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefabs/PanelRole.lh
 */
export class PanelRoleRuntimeScriptBase extends Laya.Box {
    public buttonCrouch!: Laya.Button;
    public buttonAttack!: Laya.Button;
    public buttonHeadTurn!: Laya.Button;
    public buttonWalk!: Laya.Button;
    public buttonRun!: Laya.Button;
    public buttonIdle!: Laya.Button;
}

