/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefabs/PanelGameMap.lh
 */
export class PanelGameMapRuntimeScriptBase extends Laya.Box {
    public buttonTestList!: Laya.Button;
    public buttonRole!: Laya.Button;
}

